from turtle import Turtle, Screen

timmy_the_turtle = Turtle()
timmy_the_turtle.shape("turtle")
timmy_the_turtle.color("red")
timmy_the_turtle.st()
timmy_the_turtle.forward(100)
timmy_the_turtle.st()
timmy_the_turtle.right(90)
timmy_the_turtle.st()
timmy_the_turtle.forward(100)
timmy_the_turtle.st()
timmy_the_turtle.lt(90)
timmy_the_turtle.st()
timmy_the_turtle.goto(700,50)
timmy_the_turtle.forward(1000)
timmy_the_turtle.st()
timmy_the_turtle.backward(1500)

screen = Screen()
screen.exitonclick()